package day01;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;
import java.util.stream.Collector.Characteristics;

public class SumFirstAndLastNumbers {
    
    private String challengeInput = "9vxfg\n" + //
            "19qdlpmdrxone7sevennine\n" + //
            "1dzntwofour9nineffck\n" + //
            "7bx8hpldgzqjheight\n" + //
            "joneseven2sseven64chvczzn\n" + //
            "seven82683\n" + //
            "7onefour1eighttwo5three\n" + //
            "8lmsk871eight7\n" + //
            "ninefivefive2nine5ntvscdfdsmvqgcbxxxt\n" + //
            "onepx6hbgdssfivexs\n" + //
            "cdtjprrbvkftgtwo397seven\n" + //
            "2eightsix16\n" + //
            "41pqdmfvptwo\n" + //
            "xhlqvsjpbhfivefour5sevenonemcmrkvhkjqfour5\n" + //
            "2czddtpsrgsbgddsix6gvmxqlsnnine4\n" + //
            "twozxsix9kmctfour\n" + //
            "3hqfxkzr2nineqdpgbzndxf2two\n" + //
            "bjd99eight6sfive\n" + //
            "oneeighttwo34dcjck5eightjznpzhxdlc\n" + //
            "6sixeighttqslqvplsxvpxch\n" + //
            "sixonemc55\n" + //
            "sixeight7five9ninesixfour\n" + //
            "lmbzpzrhssdslkeight9eightpjj\n" + //
            "six2eight579hlbgjnjkqrxrdlhnpfour\n" + //
            "6fkfxsqncm456onesftkndhl\n" + //
            "bqfckhdmppqvjlkx75dvjzveight8\n" + //
            "btfppljkfkzcklskgzzhmtwo9fjsix\n" + //
            "seven44tgvh\n" + //
            "rvmjm8nlg3ttgcjtwo\n" + //
            "sevendjdckvz9nine6cth\n" + //
            "dpxdpzbmnqsn8prggxn8twotwo4\n" + //
            "twofivesevenonedmkrnpznfhgh1\n" + //
            "gqeightwothreefours16gljkzgnkgclmrpsmfkq\n" + //
            "eighteightsrfcxtvg7three1two9nineeightwolqn\n" + //
            "18sixlone\n" + //
            "eight7rxfbmhnsf\n" + //
            "6twodndmhcgxlgbqbqndbbthnngblfgtzh5fouroneightrjp\n" + //
            "3vpxlzkc\n" + //
            "qpmbxctsmt38sn1\n" + //
            "threefivelxcf9eight\n" + //
            "5vsptrhgltgqnkcgn4\n" + //
            "threeseven59\n" + //
            "83eight8sevenklzjcs2\n" + //
            "three5three6twoone9\n" + //
            "fkbfvltznine2bbjpng2zhtmmhnrjq3\n" + //
            "seven1xxjfq6\n" + //
            "7btxleight4one\n" + //
            "xzsfive3rcxlczkp\n" + //
            "8bjfmkjc4dxvd9\n" + //
            "sixddfg8onetwotwosbsb\n" + //
            "gmvbngqgfour66eightcspbtjkzlxrqhfrsvfn\n" + //
            "three91djmrkkdkrrsmv\n" + //
            "four4eightlnhtvrscbf5gh5\n" + //
            "seventwo775dcg\n" + //
            "85sevenfivesixslkjbninefournine\n" + //
            "cljxdshd93rxjppchxonekmvpcmrzrv\n" + //
            "kkzkp315\n" + //
            "three3jxmvjzzvtwojsj1seven\n" + //
            "jvcfzjvfp5gsbpr5fourfour5\n" + //
            "jpfivetxmgthvlqnvjzdgrhknf4dvslqsxtv\n" + //
            "jkvtctx6kkgkeight\n" + //
            "jgsrnzzz8cf4eighteight3\n" + //
            "88eight1\n" + //
            "one674zclxfive\n" + //
            "34nlkc8threexfmlqrxbpeight3rj\n" + //
            "6six9onetgjmvqz63tnrrqlg\n" + //
            "3n67five16ninevttnvbznlq\n" + //
            "seven98\n" + //
            "5pkvtpzqs9mvpfpvhb\n" + //
            "39s1one6phcgfqbgcvhpqv\n" + //
            "sevensevenlhphq5rxffsix\n" + //
            "kvvlqzmglmqddtt87nine\n" + //
            "5npjkfhmnreightscqf\n" + //
            "954\n" + //
            "five4tmeightkfdkhdfq34eight\n" + //
            "smdqspmlv3twokthree\n" + //
            "7fivegvgfhlqsqfxdljnnpninenine429\n" + //
            "sevensixdrsltf6fnhtcssfhpl7\n" + //
            "drctwoneeighttwoninebzvhslngqjhtwo1\n" + //
            "kzeightwo14bjkksx\n" + //
            "35gglqtcjponenine4lhtjrtjzsf\n" + //
            "six4two9\n" + //
            "88dpbpbrrnceighteight3\n" + //
            "jf24sqscmzfq\n" + //
            "fourone9three2r2ninethree\n" + //
            "2fcjl2two8\n" + //
            "ndshrmtqxtwo56eight\n" + //
            "mhlsk7\n" + //
            "hcmx8792six3\n" + //
            "2sixonexgpzsjbmbqnxbtkbcvmktone\n" + //
            "trqckccvgbdjt7eight9pcnrkxbxrb\n" + //
            "sfqnzdlxqcdf56five27pfb\n" + //
            "cffn1bfjkxdvcthreetvvxfzlrrpmpmddh\n" + //
            "sxone6xzdrsdlfnn19seven8\n" + //
            "twofourtwoqxvpcjmnv3eighteightonetwo\n" + //
            "9seven453seventhree67oneightv\n" + //
            "28xmzcttr\n" + //
            "five4twohrlthrjqmthreerzprxcbj\n" + //
            "vlrdjpznp38\n" + //
            "98nphlf5ztrdzthreeddtnxrkhlzxkttpz\n" + //
            "mqbntpz6eight4\n" + //
            "28nine\n" + //
            "khkreight3\n" + //
            "1seven2fivebnjbzd\n" + //
            "cgvdfmncxdn13tp5kxvfqntveight\n" + //
            "7bkgncbfql68ninetwolfmltr8glvsdpm\n" + //
            "7onesevennine\n" + //
            "pjtmseven6mhcfrbqnmpbspsrcsixfpfkhjxdhq\n" + //
            "256one54one\n" + //
            "sonefour4\n" + //
            "vzbsj5nnhpkgkqhthreevlgfvnz6\n" + //
            "qtkrjxgrvs4\n" + //
            "four1fcglninemggpfrone2\n" + //
            "22trflsckfg7eighteightoneightrbk\n" + //
            "sevenfive5fxmbktqfive43\n" + //
            "twoonedbl1seventwokjjbv\n" + //
            "sixjlkfjnfkzfhvsj5eightmgmh\n" + //
            "gxqjmnjp5pxdksnszcrfivepeight\n" + //
            "eightthree5shxvhnzlhninefourkvchmxfj\n" + //
            "two9mjkxhsevenddtbm696\n" + //
            "3threedrs3twothree\n" + //
            "d1fivencnbrcvfcbvvphxfour\n" + //
            "sevenfkgjgrt1lzfqzksddlcprlx9six\n" + //
            "one7ckxzglncdgzxcxfour\n" + //
            "three8four6dhn3\n" + //
            "5rphkp6three2six2\n" + //
            "7ztzzlnthree4three\n" + //
            "rgxrpczczcsevenrphlhcczm985gdbjcnvjx5\n" + //
            "ggmrcxnrdxfdtd6\n" + //
            "meightwovdrpxgmpjqhpmrdsixhts86cl81\n" + //
            "4ninejdbzhtfkdnthree26\n" + //
            "9five8\n" + //
            "six276\n" + //
            "gbsphnmgz5smseven6\n" + //
            "fourgrjvpbkgninetwo1dkrcv\n" + //
            "seven96\n" + //
            "2sixninexvmxbjttxb\n" + //
            "sixnine3sixsixhvtxone7\n" + //
            "6x8\n" + //
            "773fiveeightxtrtshfivemcqxnvplx\n" + //
            "182mfcthbstt2cvqs\n" + //
            "13cone1fcgtchxpgs\n" + //
            "three45nblglcktt\n" + //
            "seventzrjngglvpcbdzfivexclqhsjdd5\n" + //
            "jhfmcqdjp8pktwoqgzskmp4\n" + //
            "pbsixtdvshb2three2lq68\n" + //
            "one9nine\n" + //
            "8six98three8\n" + //
            "7ninethree1\n" + //
            "gbpchggch74lsmfseveneight\n" + //
            "shshsjlqp7xggv2chskzzdfceightcnhrnine\n" + //
            "twoone1fdzjkdhxeight1\n" + //
            "8hdxvfblkxfive1seven3mxhv\n" + //
            "hfgmbeight9threefour9\n" + //
            "seven734\n" + //
            "three9three6\n" + //
            "dgnine4eightnineeight\n" + //
            "66nmltsclptfptxrpj\n" + //
            "5qcmvt9jhj8five\n" + //
            "532qbhhz78\n" + //
            "3bvkm\n" + //
            "34mpxdthree7nine4k1\n" + //
            "frls93\n" + //
            "sixsevenhtzjqzfthree1ninesixnpv\n" + //
            "jzqgtptsrgx4nine9txzsqghqrbnhflf\n" + //
            "7f84\n" + //
            "54sixnsdppg16nine5vcmlcqbmhb\n" + //
            "4onesixtwoghhpmgltfkxldzjh7\n" + //
            "5gncbnhztwo6eight7ninez\n" + //
            "5191jsnqmgeightwojfr\n" + //
            "bvxzrjnhnjjfvvrkvxncs6\n" + //
            "dtwo4\n" + //
            "bgckgdpdzksmlrzfone2two\n" + //
            "x98lqxzxrdrjrkbfk8\n" + //
            "6gmseven921\n" + //
            "q4eight3eight\n" + //
            "fivenkjkrcvs8hpvnrgpcthreekjfnmtg1vntwo\n" + //
            "7nine9\n" + //
            "lthqzvxmthreeonefourtwo8fourfour8\n" + //
            "vgn96cmdrnxs\n" + //
            "94fourdmfpjfbgdc7sb5xldk\n" + //
            "1eighttwodfzffvpv8eight\n" + //
            "onefivetwo1five\n" + //
            "6ttjvrlqv2fiveseven5d4\n" + //
            "87399\n" + //
            "7hblrjsxdphnplgsevendx\n" + //
            "6312\n" + //
            "vtwone4five61\n" + //
            "2fdmhrbdssf\n" + //
            "ztxbmttzvldljxrtt142tkfrfivesevenfive\n" + //
            "zz1one\n" + //
            "fivetwo98\n" + //
            "mcqggtklx39cdz7lkpxthreensztkfmc\n" + //
            "qbzmkprpfd166qhtzpcjhkqpmqrdqtcdgfhtgx\n" + //
            "95xjrltxrnp\n" + //
            "4rsjnrone85\n" + //
            "qqnhlgchvvpcrj8dmcjccthreesseven\n" + //
            "fivevbvqdftvxvgxglsevenlvrrknpk9\n" + //
            "3krqgv5fourq47\n" + //
            "ninetwosixvmt3one\n" + //
            "fcfvzrsbrqcsdhbflhkn9fdgtjxn\n" + //
            "82onekcxcvjv6dkk\n" + //
            "fkntvmx8\n" + //
            "nineljkckkldnk6\n" + //
            "twoqdptcvnine5tnmstkrsixdc\n" + //
            "ftwone6lmjlntfxptmnnnconepqszsbsbkqkvcxghmhtvsxvfldd\n" + //
            "eightfivexxhjmxvmklhzt52mvh\n" + //
            "1mmpxmsbpkf368sevennine\n" + //
            "8six3\n" + //
            "onekh1\n" + //
            "74nine6gh1bbvsevenone\n" + //
            "4pxzmslsevengdqqv\n" + //
            "five1qjfxlstfsixnine6pqqseven\n" + //
            "mgbdtwooneeight74hrfflzddfgtnmd\n" + //
            "mrsqnffrhmhjlvqthreesevenseven6fxrfmhfv\n" + //
            "two5threeeightthree\n" + //
            "ddgsixeighttwo26fourgmhg\n" + //
            "nine41g962khzsxzkg\n" + //
            "qfvdz41svzprbzthreedsfcqksix\n" + //
            "threebnbbs5six\n" + //
            "msix1\n" + //
            "three1eightoner4\n" + //
            "b2twojnrfk2zsrzqfourthree\n" + //
            "3onevqhp\n" + //
            "fjszvhmsix1\n" + //
            "hhjkjxz37nbbsjpfg28btponeightxv\n" + //
            "2six2krqlzph8\n" + //
            "5two8jmtkmpfxmkbjqxjbbvnfcgl1\n" + //
            "h2mg\n" + //
            "3seven2nine6\n" + //
            "five5qbcnsfjxm5nptwotwo\n" + //
            "6nineoneppcgf5threedcv\n" + //
            "fournjkrjn9zd2cxsfmhjtzfourphflng\n" + //
            "9seven33five1\n" + //
            "xjmhz86\n" + //
            "7sevenfivesix\n" + //
            "3kpdzzninebjzbmnklkhvn\n" + //
            "cvlcqtsix4seveneighthvhrfmsjeight\n" + //
            "1p\n" + //
            "2four3xrbhl\n" + //
            "vonerdscjkztwosj8fbxskdzk7\n" + //
            "pnx8nqjninephdhnhmc7\n" + //
            "1sevenckbxpsix5stlhknddjmgdrpm\n" + //
            "8vkltvtwo96\n" + //
            "88xccqf2fg7three\n" + //
            "four75\n" + //
            "jrcfgzddtnlmvjxgttthree1threenmrbone9\n" + //
            "27btrxjlcqftxkkjvsxnine\n" + //
            "8qvc98shcjzz\n" + //
            "cjn8three9dphltgdrscdxpv7pzrfg5\n" + //
            "27sixthree\n" + //
            "9one7nine3dvvfcztxk\n" + //
            "three82\n" + //
            "bpszb42two9\n" + //
            "twofb5gdzxbt6\n" + //
            "threecrpmqbfivefksjlxgrggb8\n" + //
            "9eight9five872\n" + //
            "vtrsixjgccvbpdppthreethree1eightjk\n" + //
            "37lh88four7six\n" + //
            "6oneseven157fourtbzdtgnkgc6eightwoqdj\n" + //
            "1two4nineoneone4\n" + //
            "2fourkqf\n" + //
            "9xbqpvlfpcfdfqxkqv233\n" + //
            "threeeight3\n" + //
            "xc9three57pnlln\n" + //
            "nineseveng1four\n" + //
            "tfivefive6\n" + //
            "ninedkf6ninerqzdrf\n" + //
            "ploneight675xmgxfrfour\n" + //
            "sevenvsixeight1pxbtmklzp9\n" + //
            "dtldflk1six\n" + //
            "fivetwo8\n" + //
            "eight2kbfmjsvst8\n" + //
            "one2qrtrfblvlnljlmnldmv7dljts\n" + //
            "six39sevenphclhsdts7\n" + //
            "bjrfrzknhctwo138four9sixeight\n" + //
            "hhttbnlrfour3fourfiveqjvzxdgrpxnine\n" + //
            "rvjvqmsscrllhmzmbdlfqlkdfcrjd67one\n" + //
            "xggzxpjmddfive5pvcdhllftb8\n" + //
            "5315one5\n" + //
            "2mtjxrxzlftmeightnineqgjpgseventhree\n" + //
            "464onenine462\n" + //
            "three6sixzstbsq\n" + //
            "1sevenone\n" + //
            "seven1pkpdeight1qlxfgqpbkzdlj\n" + //
            "1gj\n" + //
            "4dzlfbbnfourfive9kp5\n" + //
            "q8m3four9\n" + //
            "94ldqfrgnd1two\n" + //
            "38four489eighteightpr\n" + //
            "threekxr261\n" + //
            "tworgmfzsd8jjtvdlxhdpzseventwosix4\n" + //
            "tcsvdphjtgrh2\n" + //
            "nmqxclrszlhgrn3\n" + //
            "5tzxvkxbpvqgfourmlmnknxt1hjnine\n" + //
            "seven8nbvxqd1\n" + //
            "3zcqcsj6lfjvsfkfmrsplp3\n" + //
            "ts2ninetrmpjp57pbzfnfb\n" + //
            "5onesqkk82\n" + //
            "eighteight8\n" + //
            "vkmrvxhjbr3tzjlfksixseven\n" + //
            "hrlxjppxsr83dsgfxmdz6ninemlrnhz\n" + //
            "8sevenninekvjmfl35nine\n" + //
            "91\n" + //
            "35seventkx95six\n" + //
            "eight4two854five\n" + //
            "four4seven2\n" + //
            "fhbnqmlxthreeeight1\n" + //
            "7threeljeight\n" + //
            "four9cvkztds4pqql\n" + //
            "5klhghrvgng\n" + //
            "hhz8eighttwothreetwojhbxfmkjeight4\n" + //
            "two9eightwocq\n" + //
            "znj2\n" + //
            "935eight\n" + //
            "55eightkdxcmm6fivemrlbsqtvxb\n" + //
            "vzzbjkmjqktwovs5one\n" + //
            "7vqqrqhcjtzxeightthree\n" + //
            "34cfninesrcbczg91hptwo\n" + //
            "63htjrvldqmldzzqrnslzcsfmlcgjmrlnf1zjdrgzkgeightwomrv\n" + //
            "ljdpzttczjthree8five\n" + //
            "flqjdbskkp3kjmcc9nine\n" + //
            "rfcj78five\n" + //
            "ttplggc924vdkbqlcrqs\n" + //
            "ninethreeseven5\n" + //
            "5sh9\n" + //
            "four6vrrs1\n" + //
            "one7eighteight\n" + //
            "4szmhdhgdtseven62nine9four\n" + //
            "szsfkfj6cgrprx2\n" + //
            "38fourkbrlzzfhrseven2foursevenxdv\n" + //
            "3ninejcghgdchzcffxtl7eight\n" + //
            "61three\n" + //
            "kbvzkmngj35\n" + //
            "gkzrtccmg3sevenmkdcskvsone\n" + //
            "bg8txkhfiveonerdqvhrcxjrhrlndzjj\n" + //
            "4v559three\n" + //
            "ninethree4prhnsrmgq\n" + //
            "onenine2lxsixqjsxqlrzkvzcninegz\n" + //
            "444lxgckhmhxd19ngrhftc\n" + //
            "nine76lznlninesevenfsrknvktmz\n" + //
            "518onethreeeighttwo\n" + //
            "vxzkrgfshvvtdpsix99vnts\n" + //
            "nine67\n" + //
            "sixtwo2qtncmtxntfthree\n" + //
            "two5five895ccsxdphn4\n" + //
            "768\n" + //
            "jvsgtwo7sixkhkvfiveqfhjdone\n" + //
            "mqmnrqxbctwo5jtk4tg\n" + //
            "2174fjrphztmg\n" + //
            "lp4two\n" + //
            "1qldfxjmzb6\n" + //
            "one8krbtzzdgfjkrmnfnlone737\n" + //
            "3six4\n" + //
            "nineeight87threefqjgzktgnffrggb\n" + //
            "8xjhk\n" + //
            "ninesmz44fvx\n" + //
            "gktxcseven2brd28xzkflb\n" + //
            "42vfqmq8hftsixeighttwoxkfktsgn\n" + //
            "3fourzkklrbfh2hqvjmgggxrq137\n" + //
            "mthree8eightvjptjvpkhp8tvrzz5twonez\n" + //
            "sc2cbrsrtcnskjsgvd\n" + //
            "6jxhprlqpxlhkckmxxxplndps8288\n" + //
            "threegjhnbhzfn7977bfjqsqzdtjhxjpkvx\n" + //
            "9sixthree\n" + //
            "six3sixonedqgtqqzggfive7kgtksd5\n" + //
            "9djnf9htxlhkphzmthreeqxkrzpljhtx\n" + //
            "4threefivethreevxvkfour8qv\n" + //
            "eightseveneight1four5fourmvrcxvhx\n" + //
            "tdhtwone4vphnspkn\n" + //
            "onethree81pkbcljs3\n" + //
            "nspprpkgbnnine8gmfqzdlmdone\n" + //
            "vblklpvlfmtcnxgshc1threevth7\n" + //
            "3ninefivekhcvbeight427\n" + //
            "5ninesevensevengjbhfbtjgnfhtmldczcgvmfqgrtjhdmxd\n" + //
            "ninebnpvq8two4\n" + //
            "4lpsrkhmzxmffrq\n" + //
            "four1seven1\n" + //
            "threesix4\n" + //
            "twobcninegnvtcmnxmq9\n" + //
            "58sixeight1onepdgk3five\n" + //
            "mkkdvjfoursix2nmk\n" + //
            "six21bljfzdl37seven7\n" + //
            "4eightvtbrr6532\n" + //
            "jf2kxjbfvg\n" + //
            "6t\n" + //
            "51mdnkqpnine9\n" + //
            "twojqlrlhnseven2one\n" + //
            "qoneight5\n" + //
            "rmkhbb36four3vtwothree\n" + //
            "vpxfcmmj6fiveonebssninetftgngbxfive4twoneq\n" + //
            "twoseven16\n" + //
            "6lfivedpvfltcdeighttwonine\n" + //
            "7krhmggd3578\n" + //
            "vckxnbsgqm4jkjtsqrp1tvvhnfkgsghcrrxqkvb\n" + //
            "jmclhfourkqmp1\n" + //
            "jvtgthree478qxgprsxscfzngxgtgrfjfqqf\n" + //
            "xttnzjcgsxvqrxmhlcnine9two14\n" + //
            "829\n" + //
            "kmb4ninefgtjgjnxzqjmcxqpprdonesix\n" + //
            "klsnmqtwo4\n" + //
            "7pjjhtskhdvgtwoxsncbsnj\n" + //
            "mhdhkfive23seven\n" + //
            "zndrdh1xrsxmmxjvp8\n" + //
            "fktwonefcqstdshq8foureightsix\n" + //
            "kzlfqmvbqninetwo4five\n" + //
            "4sevenjffivezscdqskmfkfzltbh\n" + //
            "1782\n" + //
            "6sevenfour\n" + //
            "rleightwoqqnpsbprgtbvssjvd4\n" + //
            "brpfntx5hj\n" + //
            "rqvhgqpdz62eightthree9\n" + //
            "onejgsvzns9\n" + //
            "fournjhjlvvqpfourtwofive6\n" + //
            "7jxglnsnhbglnjsixxdhbrhgmd\n" + //
            "qznbkl9sevenfourqrnmhfeightjz\n" + //
            "1threethree5\n" + //
            "four27znfzt4298\n" + //
            "9fivejvqfdcfqtlxhhm279vl\n" + //
            "1dgvpsmnsevensix19vchfgbzpmqtdrksxczxt\n" + //
            "twospzvsmjbfqhmcd5zznpgxkfbnbsevenxkzzfhzthree\n" + //
            "4sixfpxzgblm\n" + //
            "four7sevenbvhxrjf8ffjlbnjkp\n" + //
            "73twogmnngcjsnine5\n" + //
            "3fdspqvvrmv\n" + //
            "vq8zqpzfhmmdbgqx55eighteight\n" + //
            "sixeight4jrzhqbjmcgzzxzgzcjcrg969\n" + //
            "zmsfklqskd79\n" + //
            "one85csix4\n" + //
            "9twodxfqxbhn\n" + //
            "sevensix8xbfmdtzeight4bcdcxdlxmk5four\n" + //
            "8fdvhpv8tcpqmjsbf6two9dsxrsndr\n" + //
            "jnhsclvtltwo41sixfour2\n" + //
            "mnmmdmsqlxpeight9fjgjgnmvvdxsqlcninesbglbone\n" + //
            "vleightthree7sixsxgd1\n" + //
            "dhsgn2hflhqzrxvfjbn\n" + //
            "1twofivenine2nine94\n" + //
            "threeqtgdnf8gvxfourjjrbsjgksx\n" + //
            "two8rlxcgsbdftlhx\n" + //
            "1seventhreethree7\n" + //
            "dvksvxfeightbkccpztwo6\n" + //
            "35twokpxztqnpl\n" + //
            "ctsnqstklcmcb1xhj\n" + //
            "deightwoxbrkhtgszszqspqeight91zjff\n" + //
            "onehrkvgs34twofourninennddpjtrkp\n" + //
            "2drv\n" + //
            "3rjrkmggvfive6nine6fouronethree\n" + //
            "8twonine35\n" + //
            "gqnn8ldkrjcbd4four\n" + //
            "8mtgpsflmlkcvkmffnstnqhzrfpscjhxpctvkl\n" + //
            "89threefive3\n" + //
            "sixxnvtsixxrjqvtkkb1threertdfg\n" + //
            "onenine7ndrthree5\n" + //
            "zfftwoneone59\n" + //
            "hqfzfivezpqkpptthreeseven8sixhb\n" + //
            "six298xgsfvdz\n" + //
            "sxbcgbnrlqsfhjgneightfive6two\n" + //
            "6zninenine71sevennineone\n" + //
            "txjkscxjxqvhrcmzzbxxxm6ninesix\n" + //
            "cnsr6fivefvvbdjfgrnpqkpsjbgbm\n" + //
            "tkhdhbmqbhfoursix46cbjpvqr7\n" + //
            "trbtfnsps769\n" + //
            "vkrtwonefour78onevktshzxrg9three1\n" + //
            "5vmxn8vcsxt8\n" + //
            "3eightfourpxblrzxlfx567\n" + //
            "626six1seven\n" + //
            "six3fzxsdmlpq\n" + //
            "44672ztsjrfkhk9six\n" + //
            "8smbknine\n" + //
            "seven42tt\n" + //
            "five13fivetwotwonegn\n" + //
            "98fivehpdtwofive\n" + //
            "cvthree491xrhgvlsixp\n" + //
            "four4threezkcfbqcl\n" + //
            "4six8fivefourfourtwo6\n" + //
            "8849zcrrf2threetwonevc\n" + //
            "zmzqvnnxskbbt7nine79five\n" + //
            "8cfkzkzlgdx33\n" + //
            "6gnineqj1tmmxnhntqgcrjgrcz9\n" + //
            "ninejpjzphsrsevenvtkthgtcq6onesix3\n" + //
            "seventwo1threevrpfqgrdkrnvlftwothreefive\n" + //
            "qgn4nineoneonefqfpvkb\n" + //
            "twofive5569four8\n" + //
            "9czzvcrglj86mpxctcrrninefour\n" + //
            "16one5\n" + //
            "5fiveeight8lqft\n" + //
            "36oneoneqrvqzzlvnbhnvstjrlsrnlplkccjzjx\n" + //
            "xtjgdvd3eightfb\n" + //
            "vkx2nine1gghfcrdd\n" + //
            "three3dzkxgxjvhgqvfnptmfj\n" + //
            "8hgvvlgclpl\n" + //
            "three7threefour\n" + //
            "threetxgtrvz4eighttworkd\n" + //
            "rpvlzbxs8\n" + //
            "hgmbvjfxdstpl7tnrgdjzvdtwo7bzhpcghnc\n" + //
            "kkrsprlrgslpszcxmnine44z3eightthree\n" + //
            "jxrljfivegtzbrhxmh6pqmvzf\n" + //
            "twopdvrdffbzjrckcbvp4\n" + //
            "dfms7bcmceightnine7ninethree\n" + //
            "xjpzpqtwo4three1ftpz\n" + //
            "sixeight5two3\n" + //
            "r21\n" + //
            "1twofivefiveeight47three\n" + //
            "483onehhfive9\n" + //
            "nbcfngdpqc4\n" + //
            "slnhjm3hcdnntfmbkvzthg\n" + //
            "4nine5\n" + //
            "zthninevonesixcskc8\n" + //
            "sevenckbqvmjxjx41\n" + //
            "4c\n" + //
            "nineninegmdpxkttb421jhmlxckm\n" + //
            "onesixthreeone75twoj\n" + //
            "6sdzj\n" + //
            "4xddvcvx\n" + //
            "3sixgsntt2fivethree\n" + //
            "nq1fourm5\n" + //
            "ninesld9fivesix4dxtvnzdmzvxkp\n" + //
            "ptwo8\n" + //
            "9fkvsxprvpf4five\n" + //
            "6sbjzd4vdsfvkj9fpcgqksbg\n" + //
            "kgrfsrr17twot\n" + //
            "lshfkltwo88737sevenxskzzpzg\n" + //
            "djxvsnghlm7sevenlh348\n" + //
            "4onevgcxlzmpncfflhtfrjrhf\n" + //
            "5sevenjfzkqlpmxknine6\n" + //
            "c3fourvfpzhjcppthree29\n" + //
            "zninellddrfp9\n" + //
            "3qtcxrppjseventbjvfninetwommbchqbqzx\n" + //
            "eight7sevenn\n" + //
            "qbxqpthreelvxvkprjzsncnz1\n" + //
            "8gkrxthreeeight8ltwoskdvxkg\n" + //
            "9seventwodnfghndpxtl\n" + //
            "ltwofive3jzh8two\n" + //
            "seven9qdngkndlbrhd9\n" + //
            "1m1\n" + //
            "two28fived\n" + //
            "8one3kbppsdvrn2sevenhkrfive2\n" + //
            "8one24dkzrxmdxqfourfivev\n" + //
            "dxfive11\n" + //
            "5glthvkgtzksixfoursix1\n" + //
            "jxxtpndkctfrhrssqtvv6eightchprr\n" + //
            "qdmv9kbtnk5eight83\n" + //
            "sevendkmvljcv6eightwocv\n" + //
            "lpzseven8onesbtskxjrhqhkvfblbjv5\n" + //
            "one5lvcjrkjklsfm8six7\n" + //
            "qjfvdjghsdgzmfivefive5slds7mlcsmlgnpfive\n" + //
            "tsqkjjmfhlrcfjxxsx278ninebnc\n" + //
            "threeknvkkvgpqrzbdn7six\n" + //
            "512lkhpmdntsxsixzmpcp\n" + //
            "lzvkfkmxlpsix7\n" + //
            "8fztrnfseven91sixxvbhtzghlcr4\n" + //
            "nine6891lnrfdzntsthree\n" + //
            "rvfmdl92seven\n" + //
            "tlfjnhpsix3onemhmvsthmkftbhcc\n" + //
            "3kmxcjnsm8six\n" + //
            "onethree479twolht9\n" + //
            "jdlsqp4onefour59lhdthreenine\n" + //
            "qnlpgrsrlhtwoeightfournmsbl2four\n" + //
            "lhptgljveight1vkbfx\n" + //
            "sixsdgv6fourtjltcpkbqrone\n" + //
            "nine1one1\n" + //
            "qxkrfczbpndp5gkghrqbcgcmmqrjjkxxf76dnjbnfc\n" + //
            "3nineseven99xhmndd94\n" + //
            "6875twonefns\n" + //
            "24threeeighttwo\n" + //
            "3six1threeeightsix2sixp\n" + //
            "xvone27fvmdd11four\n" + //
            "6eightwolhn\n" + //
            "gseventwobbj9bfrtdzsrjone7qz\n" + //
            "twopbfdzddqninern5gxzbqcj\n" + //
            "5four4sixfivefb\n" + //
            "88xtkpjtthreefourtcldldhk\n" + //
            "mnbxx1\n" + //
            "2dvfour2\n" + //
            "eightfvrsnk27\n" + //
            "fivexfnblfpp77qfour1mrfrphbg\n" + //
            "6lgddqkjqheight\n" + //
            "rvtwonemdxgfsgnnc98hmonexvmhkzkmjt\n" + //
            "two6cglzbdklmjqjncn5xptwovtbhvmgsd\n" + //
            "sevenkvxn6\n" + //
            "8eightjkmtncbrv8199six\n" + //
            "sixd14six665\n" + //
            "gbkfpnnjxpmdfivettvdpnbrk16xdnhqkrpljfq\n" + //
            "58vgmvzx\n" + //
            "onetxxzl9fivelhcfpkvrsgn4\n" + //
            "25two6mcrvbkxrtltrbsfour\n" + //
            "517\n" + //
            "rvqq6ninekfmninefiveseven\n" + //
            "five2jp\n" + //
            "qvlcmsqpvmjbjknvlknzfxcqp5\n" + //
            "1ttsbmjz8bmgrjvtrrthree8dlrjeightrjjvcbcpmv\n" + //
            "95sixtwonine1\n" + //
            "tkpjkpbq16\n" + //
            "lstsfrltcm1qbzx9\n" + //
            "three713three\n" + //
            "onetwo4eightfivefive\n" + //
            "7sixxcfive\n" + //
            "52two9\n" + //
            "xngd1\n" + //
            "8eightvmktwo4eight\n" + //
            "sixgjjgvtznrskhxnsonetwoqdhtone21\n" + //
            "9fftwo3\n" + //
            "5ninevmlvmjnxvb91fourqbnnfcz\n" + //
            "hpcmsgseven2sdp82eightwot\n" + //
            "3five8\n" + //
            "jnxd6\n" + //
            "3vfgbml831dkbqsix93\n" + //
            "6pdlllrll3mskssmddnine8three6\n" + //
            "4vsdqddkfivethree11pklbpk\n" + //
            "47five\n" + //
            "58fivefptcc3xfqvkxqmd\n" + //
            "eight94mrvtn93eight8\n" + //
            "6fdlbrbbninebmdptsfdzmeightzqmxvpptps\n" + //
            "1ninegcgcrcgbvtfptlgdthreenflkdhjqjctwoneh\n" + //
            "8ppqpvrphfhrkgqjrseven\n" + //
            "knklcdrcrcjt545\n" + //
            "ztmqxsevenhpqtgknssnnvdssfpxztwo8threeseven\n" + //
            "xnhoneightf2five\n" + //
            "r3tworkmgkqvtf77qtbxg\n" + //
            "threeone41five57\n" + //
            "fpsix7jrkmmxlhqknjbldthree38\n" + //
            "pzxlnfj2\n" + //
            "sevensevenkbjfvtfzbvgjvzkmnb8eightgggzbz9\n" + //
            "zqkvgk3\n" + //
            "vcpvzhxsxcglhtvmcn2zmqjkxconeonesrdmmmhgjrgkszhxj\n" + //
            "dfjhvgftwo1\n" + //
            "8fivetwofoursix8fivenine\n" + //
            "rfive5eighttfn1\n" + //
            "fourrnine4bh\n" + //
            "gnh9nine4pbbj\n" + //
            "4129four22llnx5\n" + //
            "cvdrdzlbmhjchfmvdhhztf4dxnrpvr\n" + //
            "31fourfivegl2\n" + //
            "hp2eight2klkzlthmd2\n" + //
            "8mzghdpvjkseven667\n" + //
            "eightfourthreehhxjkljdeight9twoone\n" + //
            "d519\n" + //
            "zlcncbrbnlblfxjtntjkmh4939\n" + //
            "3484eight9five1one\n" + //
            "6two365vvllsqcsmrzqnfgrf\n" + //
            "qqtntflfoureightdhzrgg84eight\n" + //
            "43ndrxmkznbnseventwotfckg9five\n" + //
            "gqxghcjtmnine1\n" + //
            "622\n" + //
            "nxfdgdgmnd6ninedqnfnvnlkoneeightwob\n" + //
            "nhnfgxrninesix47\n" + //
            "9nine8jvqrv4two\n" + //
            "ldjklnnfour31oneeight3\n" + //
            "dfhdmtqrttln5five41\n" + //
            "4seven1six52\n" + //
            "6nz498sixhbsbjxbzxr\n" + //
            "gpx4four5246\n" + //
            "nqzsqjhqmrninedfxkmnine9431mdgbkn\n" + //
            "ghdfpkxkgtjbsqvmqjsbgljrpbqggpgptwofour8\n" + //
            "2pmckttc3663rkshqjmvm\n" + //
            "1seven7gzsevenks8\n" + //
            "tchrd7nq44\n" + //
            "pljkrthree2\n" + //
            "four57\n" + //
            "five138\n" + //
            "k36\n" + //
            "fivednxrs818\n" + //
            "three6eight96eighthvpcrldfiveqkglq\n" + //
            "fivezbnmsevensix3eight\n" + //
            "qbfeightwofour3pcr1sixseventwo\n" + //
            "three4two7\n" + //
            "fivetrdfdqpbt15\n" + //
            "26nine1\n" + //
            "3sevenq8eight\n" + //
            "two669six\n" + //
            "5p4eight219rgkj\n" + //
            "76four\n" + //
            "jrmnkp1224qrzg6\n" + //
            "29eightninelvkxbt8\n" + //
            "seven7vq\n" + //
            "lgrgxxk2sbxbcvmjqqs\n" + //
            "4threesixshtxpgdhnine38\n" + //
            "6fcmmzhgnmm8\n" + //
            "lxrtjvqzmzeight2ninept\n" + //
            "2hqd93sixone2nine\n" + //
            "m1\n" + //
            "4five5threesixnine\n" + //
            "7sixfxrbr\n" + //
            "eightsix369one\n" + //
            "foursix7seven2bmrqmkb7dbvzrk\n" + //
            "35seven4onesmsbgbxlh2oneknnlnrg\n" + //
            "hmsevenfour84eighttwo\n" + //
            "eight73sevenseven555jklfjnrts\n" + //
            "ktqbgzvdqdcbreightjkjz4dxnfpfgjs1fvfpbczvt\n" + //
            "xflxseight7smkkkdqsrgoneightx\n" + //
            "9sixfive3nineonebfqbptl\n" + //
            "rkxtmcltxjeight3fivetwomsjpjdm\n" + //
            "4bldszkxzrq1threetd\n" + //
            "gnpthree5one\n" + //
            "3onesevenvbfghbzksrlkl63seven\n" + //
            "6xjqqsztdsnine1fournine3eight\n" + //
            "8957four17\n" + //
            "three75\n" + //
            "5zlsixtwo78\n" + //
            "mjqtlfqztt55eightpsevensevenkrdrvsqxjtphpp\n" + //
            "rztvsc9four5jsrcnvc\n" + //
            "2fgstpfournine\n" + //
            "onesjjhlcg1nineknqhlr\n" + //
            "ldfone9\n" + //
            "threernszcbdxjdhbmg1eight4\n" + //
            "klkmktxqfz4qcvptvdtwofive8\n" + //
            "3sbpvfxpsvpsnine7nine\n" + //
            "threexdsbxxrxmmndql19pxzvj\n" + //
            "1cbn7hvhggznffkp\n" + //
            "41f\n" + //
            "hdmgqzrhdhseven25zdjdqrrpksixtwo\n" + //
            "2two7ninesixscd\n" + //
            "two5twojjvkjbs\n" + //
            "eightsix186twonelp\n" + //
            "xpdskdkmjb5hhnkcnxrdbnpj\n" + //
            "96fourfour\n" + //
            "7one22\n" + //
            "1one2qkjszlfourtwoeightgmlfkgsm3\n" + //
            "klqmpxqzhhhk1sixqmmfnmbllqjkvlqdz\n" + //
            "nmgjmhsevensix799\n" + //
            "rrgpsbmnine9ninebqdgnxfsix\n" + //
            "xrmslkfkzfiveninefzzbn7eightndscmjqsldlclkmsxbtjstzds\n" + //
            "bqrjjrbgsixsixjgds1\n" + //
            "7fmtncmjbgcvhfhlhzzdlltpdscszrlmk88\n" + //
            "fourchvjlhzxxtwo94\n" + //
            "six2one78vkrqvp2sixvhtmqngtk\n" + //
            "fknxmgcljbxfkkbdkbl868nine9\n" + //
            "height12fjt\n" + //
            "knrlb2ninesevenpzjd\n" + //
            "threefourkxtmnxbtfiveeight98fvnkvrx\n" + //
            "3xxszc\n" + //
            "vhp2rxfrhteightkfive\n" + //
            "cxlzglbnineeightsixxlphhkkkl7eight\n" + //
            "lcltksrvsevensixsixtssrszb55\n" + //
            "21sjzxsqvlj1seven293j\n" + //
            "3gkjdshvxkfmxnfkqhpfour56\n" + //
            "kgdbqsmxxqone3p4\n" + //
            "3m7hmbctwo297\n" + //
            "4vvr5\n" + //
            "eight11\n" + //
            "nine1six74vzdllp\n" + //
            "1nine9756sxr6\n" + //
            "9sevenfourtwovxbshb\n" + //
            "qcgztnjjvvfiveghlbr7\n" + //
            "nfgngg7fntfv\n" + //
            "threeftwonndpzp681\n" + //
            "llbmvrfive5slpjkrpslcthreer\n" + //
            "eightrgmglgds3ggddvtfbrddhpktz\n" + //
            "75nineonethree6fourseventwonek\n" + //
            "2226\n" + //
            "4twokt8\n" + //
            "2svschdf58eightzpsk1\n" + //
            "gqxthreetmfourcqvzponethree2\n" + //
            "rbsvrl616\n" + //
            "8threeghjeightshsnheightrvrfhvzgeight\n" + //
            "6klzknkbkxg76cs38\n" + //
            "vfive4cxrnmkfnmf54cffsnrsbhjtwo\n" + //
            "twozclqgkdfmqfzvjxzbfonetwo5tgrfive9\n" + //
            "hphppvb43ninefive3\n" + //
            "3tx76threeninefqdtspfxqvq\n" + //
            "5twoltwo6lvqsfd4\n" + //
            "bvzcthreeqxbjrnnm5\n" + //
            "61five\n" + //
            "nine1fgsdjvdfrl9ninefour11d\n" + //
            "hfzkbvmbrbh866ninefour\n" + //
            "4spfmhsdbqn\n" + //
            "fbgqhzpffhfvrnflhttrmx7fourfourrrfrcrnbbcsix\n" + //
            "xczblxnpjjhbxlpffzchjvhhj98jkhvjphb\n" + //
            "two17x\n" + //
            "twodkg2three\n" + //
            "4ninefour2grfive1eight\n" + //
            "sfsvv5nineninevgshrjonefiveone5\n" + //
            "fiveqqpggmmptjcg5seveneight4threejqpn\n" + //
            "8sevenfoureightthreegrrjlgn9\n" + //
            "6fnmtzfqfive72three8\n" + //
            "7nine7\n" + //
            "1threelhddbxnndpsgxnb\n" + //
            "73mpcjnhcn\n" + //
            "2knbcxnnfvthree\n" + //
            "two4kmbrxzrqgtnineftjlslgdz\n" + //
            "f36992ninefour\n" + //
            "26fourninesixthree\n" + //
            "zvggfbznineone85nine\n" + //
            "three7threehfour\n" + //
            "4eightxq7vxdqxjdntc\n" + //
            "8nineprhgqb9rvkcssflvck2bghnf\n" + //
            "kbkjxjs4eight188rjlmmdgcvr7\n" + //
            "fnkcbmdmbmnglztltrbcnineone6\n" + //
            "7jjgtlt821\n" + //
            "78xfgxrtm6four\n" + //
            "9k5five\n" + //
            "four764one\n" + //
            "4pmdqzcceight6sevenrl5seven\n" + //
            "ckhvfc92jdrxzxhzgsnkj45\n" + //
            "sgveightwolhl8one454pmcmks7\n" + //
            "hlpbfkqtnjoneeightjnpt9\n" + //
            "tnine8\n" + //
            "ddlhfqglnftnd4\n" + //
            "pdpdvdgdr3twofqzjqqjp8sixtwo\n" + //
            "jq4onetlpzllzmk\n" + //
            "twoseventwotwobpone1twok\n" + //
            "3759qbxgjfivenine4\n" + //
            "vhxhh31\n" + //
            "cbfkfld3one54\n" + //
            "bpchvxkvtone4npnkccpchvf16sixrpcrftmc\n" + //
            "3sixeightmhvbxthree\n" + //
            "2six5qeighttxgfour41\n" + //
            "vjchfvn88kjsdzvkzphlhgsvseven5\n" + //
            "823nineqd369\n" + //
            "377\n" + //
            "8ninethree7\n" + //
            "jvvvz4\n" + //
            "mldjxseven2\n" + //
            "two2xvjrjvqsx8\n" + //
            "ftwo91\n" + //
            "zhndzkhzcqone332\n" + //
            "vcssgkmvneightcdhm1przq\n" + //
            "8tfvgcheight76\n" + //
            "zqxthsnine7nine\n" + //
            "onezsklndhqllfourfive24qmlvgtm7\n" + //
            "jgh8h1six\n" + //
            "six23\n" + //
            "threehxhvsqpcxrnrpggtwoxtptrlt95\n" + //
            "rhcxxeightthree444djzcckrst\n" + //
            "9onensgone1eightmfkftpsfctqmn\n" + //
            "55eight\n" + //
            "656cpbmgsevenrsqd2onefour\n" + //
            "3sevenbjlggzzfzxnhkzxtbpgxqbrfgtb4\n" + //
            "3hhbrdtmmrzssfmtv8\n" + //
            "28szkfjnzrcv\n" + //
            "7twopthree\n" + //
            "hnp42\n" + //
            "5rxg6\n" + //
            "twoeightnfhdbndrtzltninehdtkheight4eightwolpr\n" + //
            "33sevenmggst\n" + //
            "2fiveseven\n" + //
            "fhfrmgnsfcthree849bznbtbfourfive\n" + //
            "1twooneone1four\n" + //
            "fourxlvsgqzzpkzgmsixtwo63\n" + //
            "nmcmgkfdt2fiveeight7\n" + //
            "qnhjdccdqdnine41tjzbpzmztwo7\n" + //
            "1eightkqftvgmgqnqqgvghvhds4\n" + //
            "49seven59\n" + //
            "6trfive9\n" + //
            "sixbtrqxgsdjl6three\n" + //
            "eight4seven\n" + //
            "14xblhzfdbxeight\n" + //
            "sixlbthqhcmrn7five2eight3\n" + //
            "tpltwonejjvqkz8onelgndpsvxzninenineseven\n" + //
            "sevenfive8twonez\n" + //
            "dkzrpvtkhq664pnine\n" + //
            "nine1m6\n" + //
            "ltwone1fourphtqthreethree1foureighttwo\n" + //
            "threegmlxrnbkmjfvlbmdhn4mcchtmcninetwodtz\n" + //
            "ninerknt1sixsevenfive\n" + //
            "6vzpjhtwonemc\n" + //
            "sixsevenninexmf6five1\n" + //
            "qrkvjcdvnkh1ssfmqxqmnine83three\n" + //
            "8cjtsf6hmmnveightsix82\n" + //
            "zphqxnsevenjklnhmfphcfoursixtbmtmkeight5\n" + //
            "3sevensevendnxdrqskvx\n" + //
            "vpltgsevenpkbspnfzc5qmbdb\n" + //
            "fiveseven5dgkdpjxtzvffqvltwo38\n" + //
            "ninesxljqcmmqf3two\n" + //
            "one19mgdbsmsonethree73lmdchhccc\n" + //
            "27six\n" + //
            "vd6seven946h\n" + //
            "fourthreerqcnchsfourthreefourgghcmcjvfv4\n" + //
            "mmjhninefiveseven5\n" + //
            "8eighttls2\n" + //
            "bcconeblccrjckjpr5tqbvpm9\n" + //
            "1rggt418threevmjhkdztqm5\n" + //
            "687jzfltlveightone1\n" + //
            "nine5seven4ninexmgnmpqnc\n" + //
            "6cbthree2\n" + //
            "mdhrs4tqddtrhzxscxxggkgcfiveone\n" + //
            "5rjfldggflcslhkkjllthree631\n" + //
            "94pxssc6eighteightfivesix\n" + //
            "fivezmjqnlfggqzsix9\n" + //
            "fivefour369five5\n" + //
            "4stgkns3xz\n" + //
            "threenine1\n" + //
            "7qttnmpld89fivetpxgzjhgjpcrhm\n" + //
            "eight158\n" + //
            "16one\n" + //
            "ninefqbmlkkkhppbvlljbeightc6onefkthmhktkbdjc\n" + //
            "eight533gzndzbl7sevenninefive\n" + //
            "fournine6\n" + //
            "49pscnggt6one4\n" + //
            "six2seven2fourmeight\n" + //
            "xdvvgsevenjpdjtl7eight6onerj5\n" + //
            "cdmcsjbt7fivevvczqvdpqqcnxttk1two\n" + //
            "fivefourfivespmgsfghdqmpqqvngj6\n" + //
            "6fkrqlc\n" + //
            "qffdddhmxck23nvnqmczxpvnb8eighttwo\n" + //
            "j6xhzcgskqzk9qtnine3\n" + //
            "three224vdsix\n" + //
            "qhl8lzcvdskb\n" + //
            "six9hxgm\n" + //
            "six3lm8xgptktfbml3\n" + //
            "3twofive1threeeight6\n" + //
            "933seven7sspmm\n" + //
            "vvxkvmlpzn7\n" + //
            "2six6onempljqttngeightgrzkxxsbqb\n" + //
            "fourtjgmd254two\n" + //
            "jptqbmvninenqx69\n" + //
            "cqcsfmzx4kvrcpjm\n" + //
            "jmmmb4mpdxrkvqc5dthree1seven\n" + //
            "psmpdnmb3hthree\n" + //
            "5612zvndmk\n" + //
            "cdfmfrxrhvsevenbpvpxtsmr9two3\n" + //
            "six7fourt1sixtwo\n" + //
            "9sevenfour4fdzseven5vdcgvqsix\n" + //
            "dffpldbfourjlklt99\n" + //
            "vhmbrd8qhglxdgninefourdnvcdzfzhssqnmfnlgeightrvff\n" + //
            "sfxkfhx8\n" + //
            "qglscpbxzffivenineone41hbzgjfzzvghtrklp\n" + //
            "rrzvzbqkjl4\n" + //
            "sixfour1zkqtmrkhm26six\n" + //
            "2rqdcxnine76seven9five\n" + //
            "8lxnzzt514\n" + //
            "gdhdz572bhbhqhrhxdninebvv\n" + //
            "3one68eightvjtrqg\n" + //
            "8775mdcqcjthreehhrshdbtss19\n" + //
            "ddgjkksvhseven22dqsclbgl\n" + //
            "six7vdsix4\n" + //
            "fsbtxfmdzlfxqxpfdxl65sixjpvpkjhqp\n" + //
            "l4r3mgjninedqh\n" + //
            "four2cmk6twoczsnqddjdxgm3three\n" + //
            "gsmhmkfsz8mfninehx\n" + //
            "5dhgpmdjmdvpvmbone995qdhmmjlg\n" + //
            "tfour35636fiveseven\n" + //
            "vfdv8bzvjqbfpsix\n" + //
            "sixdgfqgxfvr6tdzhzkzknbl\n" + //
            "fivefoursix83eightsevenrcqprm\n" + //
            "eightzxxvckndp58zpq\n" + //
            "66one\n" + //
            "8xlgdrjnhxphtsstrptninetwojgvkrprtzklcpjbp\n" + //
            "8fzdtf\n" + //
            "8hkljkkck5\n" + //
            "onefivesix6nllxhcczxdszxnxpxbpthree15\n" + //
            "85oneighttx\n" + //
            "1fiveqkvflmzsgdxnnthreefour\n" + //
            "8fczsixone9sixfive\n" + //
            "eight9onedtvszfxsqpvdzmsevenfivejghsqvkhn\n" + //
            "foursevendmrgdbngndeight6fivendmgxkh\n" + //
            "4446\n" + //
            "9kbrmsm2eightsfxvldhgsznrlqsixhtfxxllm9\n" + //
            "8trchslhdfxxhrrkonesix74twoone\n" + //
            "eightnine5cfsrfjpxh141\n" + //
            "four6nine6\n" + //
            "threenmxeightseventhree9threevqzfg\n" + //
            "three9fournineeight25\n" + //
            "four5nhd\n" + //
            "nrkzspjpmfcqxthreerxpxlcknn1rkhggsix\n" + //
            "kzrdjnvxfone5sixsixrdnbvgtwo7\n" + //
            "ninethreefive3vmc63ninebkccndnmq\n" + //
            "seven89eight8fjtfzqlrbmnine9r\n" + //
            "lbhkmjxx46one4\n" + //
            "32121nine2\n" + //
            "seveneighttskhdjninezzfh4clnhstsnine\n" + //
            "9fourcvhseven\n" + //
            "pbheightwobpcpfzqfxone6onejmmmtgvhtfour\n" + //
            "62rkfnbkjkqzthree4twoeight15\n" + //
            "six1jgpvqtwo378\n" + //
            "4stwosevenxfnqcmglgzxtrbhvd\n" + //
            "nkoneightq35srthgtnjpd\n" + //
            "three6ctx1fiveeight\n" + //
            "eight9eighttnthsddmfz8mktrsix4\n" + //
            "eightpmqqxfqcffour8xflgdscrzmbjhjq1four\n" + //
            "648one\n" + //
            "threesix88zdsbmsmch5\n" + //
            "fourdpkgxggzvm3\n" + //
            "262\n" + //
            "597onethreenine\n" + //
            "2zsgllcmjz8hvvgbzxpv29qdqnfrj\n" + //
            "63lxzjglsk59\n" + //
            "5nineclzblmhqzoneninesixm\n" + //
            "6eighteightfour9threehnine\n" + //
            "pjrqcmrntwo5g346hhstlmgx\n" + //
            "fhgkhdhqbzrlone9fiveknjmthreethreejqgbgmvxlq\n" + //
            "onesixmhhfckkhcbzffthreegp6\n" + //
            "foursixkbvzvnsdtggpb68onefourctst\n" + //
            "6zlrrqdnineqfjjq\n" + //
            "4bx\n" + //
            "dqnsix1onefqlsqlmtlcgpsfrkcx\n" + //
            "4three2czjxqbf8s4vhsc\n" + //
            "fourtwomdfiverfmsgzfour6one\n" + //
            "qgpctkpdoneonefive2\n" + //
            "vks66\n" + //
            "four5725eight\n" + //
            "tdrxflfkpgtwo35three\n" + //
            "eightfivebxs3\n" + //
            "8four4298gtfqnmqvqd\n" + //
            "7jhvtfxs\n" + //
            "961cvmsbzkonefive2\n" + //
            "rdkfxsix4tnmndhnxnv86\n" + //
            "two4dddpmrhh7fourthreeeight9\n" + //
            "slhdsxngfxszspppxxfftmxlptzhtwovp1\n" + //
            "4vmzcrhtdvnm6zfive5pkbhcxj";

    public void sumFirstAndLastNumber() {
        Integer totalSum = 0;

        for (String input : this.challengeInput.split(("\n"))) {
            totalSum += Integer.parseInt(this.getNumbers(input));
        }
        System.out.println("Challenge 1: " + totalSum);
    }

    public void sumFirstAndLastNumberInChar() {
        Integer totalSum = 0;

        for (String input : this.challengeInput.split(("\n"))) {
            String convertedInput = convertTextNumbers(input);
            totalSum += Integer.parseInt(this.getNumbers(convertedInput));
        }
        System.out.println("Challenge 2: " + totalSum);
    }

    private String getNumbers(String input) {
        char firstNumber = ' ', lastNumber = ' ';
        for (int i = 0; i < input.length(); i++) {
            if (Character.isDigit(input.charAt(i))) {
                if(firstNumber == ' ')
                    firstNumber = input.charAt(i);
                lastNumber = input.charAt(i);
            }
        }
        return Character.toString(firstNumber) + Character.toString(lastNumber);
    }

    private String convertTextNumbers(String input) {
        Map<Integer, String> containedNumbers = new TreeMap<Integer, String>();
        Map<String, Character> allNumbers = new HashMap<String, Character>();
        allNumbers.put("one", '1');
        allNumbers.put("two", '2');
        allNumbers.put("three", '3');
        allNumbers.put("four", '4');
        allNumbers.put("five", '5');
        allNumbers.put("six", '6');
        allNumbers.put("seven", '7');
        allNumbers.put("eight", '8');
        allNumbers.put("nine", '9');

        StringBuilder inputBuilder = new StringBuilder(input);

        for (Map.Entry<String, Character> Number : allNumbers.entrySet()){
            if(input.contains(Number.getKey())){
                var first = input.indexOf(Number.getKey());
                var last = input.lastIndexOf(Number.getKey());
                containedNumbers.put(first, Number.getKey());
                containedNumbers.put(last, Number.getKey());
            }
        }

        for(Map.Entry<Integer, String> Number : containedNumbers.entrySet()) {
            inputBuilder.setCharAt(Number.getKey(), allNumbers.get(Number.getValue()));
        }

        return inputBuilder.toString();
    }

    public static void main(String[] args) {
        SumFirstAndLastNumbers sumFirstAndLastNumbers = new SumFirstAndLastNumbers();
        sumFirstAndLastNumbers.sumFirstAndLastNumber();
        sumFirstAndLastNumbers.sumFirstAndLastNumberInChar();
    }

}
